# Generated by Django 4.0.6 on 2025-03-26 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pl2Spread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pl2SpreadRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_title', models.CharField(max_length=200)),
                ('artist_name', models.CharField(max_length=200)),
                ('album_title', models.CharField(max_length=200)),
                ('release_year', models.DateTimeField()),
                ('artist_genres', models.CharField(max_length=200)),
                ('artist_popularity', models.CharField(max_length=100)),
                ('song_popularity', models.CharField(max_length=100)),
                ('playlist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pl2spread.pl2spread')),
            ],
        ),
    ]
