# Generated by Django 4.0.6 on 2025-03-27 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pl2spread', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllPlaylists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_id', models.CharField(db_column='playlist_id', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pl2SpreadPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_title', models.CharField(max_length=200)),
                ('artist_name', models.CharField(max_length=200)),
                ('album_title', models.CharField(max_length=200)),
                ('release_year', models.DateTimeField()),
                ('artist_genres', models.CharField(max_length=200)),
                ('artist_popularity', models.CharField(max_length=100)),
                ('song_popularity', models.CharField(max_length=100)),
                ('playlist_id', models.ForeignKey(db_column='playlist_id', on_delete=django.db.models.deletion.CASCADE, to='pl2spread.allplaylists')),
            ],
        ),
        migrations.RemoveField(
            model_name='pl2spreadrow',
            name='playlist_id',
        ),
        migrations.DeleteModel(
            name='Pl2Spread',
        ),
        migrations.DeleteModel(
            name='Pl2SpreadRow',
        ),
    ]
