# Generated by Django 5.2rc1 on 2025-03-27 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pl2spread", "0002_allplaylists_pl2spreadplaylist_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Playlists",
            fields=[
                (
                    "playlist_id",
                    models.CharField(
                        db_column="playlist_id",
                        max_length=200,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tracks",
            fields=[
                (
                    "track_id",
                    models.BigAutoField(
                        db_column="track_id", primary_key=True, serialize=False
                    ),
                ),
                ("track_title", models.CharField(max_length=200)),
                ("artist_name", models.CharField(max_length=200)),
                ("album_title", models.CharField(max_length=200)),
                ("release_year", models.DateTimeField()),
                ("artist_genres", models.CharField(max_length=200)),
                ("artist_popularity", models.CharField(max_length=100)),
                ("song_popularity", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="pl2spreadplaylist",
            name="playlist_id",
        ),
        migrations.CreateModel(
            name="TracksPlaylist",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "playlist_id",
                        "track_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "playlist_id",
                    models.ForeignKey(
                        db_column="playlist_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pl2spread.playlists",
                    ),
                ),
                (
                    "track_id",
                    models.ForeignKey(
                        db_column="track_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pl2spread.tracks",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="AllPlaylists",
        ),
        migrations.DeleteModel(
            name="Pl2SpreadPlaylist",
        ),
    ]
